/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FacturasRouteImport } from './routes/facturas'
import { Route as FinanzasRouteImport } from './routes/finanzas'
import { Route as PacientesRouteImport } from './routes/pacientes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturasRoute = FacturasRouteImport.update({
  id: '/facturas',
  path: '/facturas',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanzasRoute = FinanzasRouteImport.update({
  id: '/finanzas',
  path: '/finanzas',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesRoute = PacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/facturas': typeof FacturasRoute
  '/finanzas': typeof FinanzasRoute
  '/pacientes': typeof PacientesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/facturas': typeof FacturasRoute
  '/finanzas': typeof FinanzasRoute
  '/pacientes': typeof PacientesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/facturas': typeof FacturasRoute
  '/finanzas': typeof FinanzasRoute
  '/pacientes': typeof PacientesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/facturas' | '/finanzas' | '/pacientes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/facturas' | '/finanzas' | '/pacientes'
  id: '__root__' | '/' | '/facturas' | '/finanzas' | '/pacientes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FacturasRoute: typeof FacturasRoute
  FinanzasRoute: typeof FinanzasRoute
  PacientesRoute: typeof PacientesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturas': {
      id: '/facturas'
      path: '/facturas'
      fullPath: '/facturas'
      preLoaderRoute: typeof FacturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finanzas': {
      id: '/finanzas'
      path: '/finanzas'
      fullPath: '/finanzas'
      preLoaderRoute: typeof FinanzasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes': {
      id: '/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof PacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FacturasRoute: FacturasRoute,
  FinanzasRoute: FinanzasRoute,
  PacientesRoute: PacientesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
